influxdb:
  persistence:
    enabled: true
    size: 10Gi
  setDefaultUser:
    enabled: true
    user:
      username: "admin"
      password: "zaq12wsx"

grafana:
  persistence:
    enabled: true
    size: 10Gi
  adminPassword: "zaq12wsx"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: InfluxDB
          type: influxdb
          url: http://monitoring-stack-influxdb.monitoring:8086
          username: "admin"
          password: "zaq12wsx"
          database: influxdb
          access: proxy
          jsonData:
            httpMode: GET
          uid: influxdb  # Specify the UID for the datasource

telegraf:
  config:
    inputs:
      - cpu:
          percpu: true
          totalcpu: true
      - disk:
      - diskio:
      - kernel:
      - mem:
      - swap:
      - processes:
      - system:
      - statsd:
          allowed_pending_messages: 10000
          metric_separator: _
          percentile_limit: 1000
          percentiles:
          - 50
          - 95
          - 99
          service_address: :8125
    outputs:
      - influxdb:
          urls: 
            - "http://monitoring-stack-influxdb.monitoring:8086"
          database: "influxdb"
          username: "admin"
          password: "zaq12wsx"
          write_consistency: "any"
          timeout: "5s"
          user_agent: "telegraf"
          insecure_skip_verify: true

